CREATE USER SA_PIZZERIAS
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_pizzerias_data_01;
GRANT CONNECT,RESOURCE TO SA_PIZZERIAS;

CREATE USER SA_PIZZA
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_pizza_data_01;
GRANT CONNECT,RESOURCE TO SA_PIZZA;

CREATE USER SA_COUNTRIES
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_countries_data_01;
GRANT CONNECT,RESOURCE TO SA_COUNTRIES;

CREATE USER DW_CL
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_dw_cl_01;    
GRANT CONNECT,CREATE VIEW,RESOURCE TO DW_CL;


CREATE USER DW_DATA
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_dw_data_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DW_DATA;


CREATE USER SAL_DW_CL
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_dw_star_cls_01;

GRANT CONNECT,CREATE VIEW,RESOURCE TO SAL_DW_CL;

CREATE USER SAL_CL
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sal_cl_01;

GRANT CONNECT,CREATE VIEW,RESOURCE TO SAL_CL;



CREATE USER DM_DATE
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_date_01;

GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_DATE;


CREATE USER DM_LOCATION
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_location_01;

GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_LOCATION;


CREATE USER DM_PIZZERIAS
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_pizzerias_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_PIZZERIAS;

-- User: DM_THEATER
CREATE USER DM_OWNER
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_owner_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_OWNER;

CREATE USER DM_PERIOD
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_period_01;

GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_PERIOD;


