alter session set current_schema = SA_TRANSACTIONS;

--daily pizza orders by pizza_name CUBE
SELECT  CUSTOMER_SALE_DATE, PIZZA_NAME, COUNT(*) AS pizza_order
FROM sa_transactions
GROUP BY CUBE(CUSTOMER_SALE_DATE, PIZZA_NAME)
HAVING CUSTOMER_SALE_DATE IS NOT NULL AND PIZZA_NAME IS NOT NULL 
ORDER BY CUSTOMER_SALE_DATE, PIZZA_NAME DESC;


-- daily report for the country CUBE
SELECT  CUSTOMER_SALE_DATE,COUNTRY_CITY_CUSTOMER,COUNT(*) AS pizza_order
FROM sa_transactions
GROUP BY CUBE(CUSTOMER_SALE_DATE,COUNTRY_CITY_CUSTOMER)
HAVING CUSTOMER_SALE_DATE IS NOT NULL
ORDER BY CUSTOMER_SALE_DATE,COUNTRY_CITY_CUSTOMER DESC;

-- daily report for the pizza_size CUBE
SELECT  CUSTOMER_SALE_DATE,PIZZA_SIZE,COUNT(*) AS pizza_order
FROM sa_transactions
GROUP BY CUBE(CUSTOMER_SALE_DATE,PIZZA_SIZE)
HAVING CUSTOMER_SALE_DATE IS NOT NULL
ORDER BY CUSTOMER_SALE_DATE,PIZZA_SIZE DESC;

-----------------------------------------------
-----------------------------------------------
-----------------------------------------------

--month pizza orders by pizza_name CUBE
SELECT  EXTRACT(MONTH FROM CUSTOMER_SALE_DATE), PIZZA_NAME, COUNT(*) AS pizza_order
FROM sa_transactions
GROUP BY CUBE(EXTRACT(MONTH FROM CUSTOMER_SALE_DATE), PIZZA_NAME)
HAVING EXTRACT(MONTH FROM CUSTOMER_SALE_DATE) IS NOT NULL AND PIZZA_NAME IS NOT NULL 
ORDER BY EXTRACT(MONTH FROM CUSTOMER_SALE_DATE), PIZZA_NAME DESC;


-- month report for the country CUBE
SELECT  EXTRACT(MONTH FROM CUSTOMER_SALE_DATE),COUNTRY_CITY_CUSTOMER,COUNT(*) AS pizza_order
FROM sa_transactions
GROUP BY CUBE(EXTRACT(MONTH FROM CUSTOMER_SALE_DATE),COUNTRY_CITY_CUSTOMER)
HAVING EXTRACT(MONTH FROM CUSTOMER_SALE_DATE) IS NOT NULL
ORDER BY EXTRACT(MONTH FROM CUSTOMER_SALE_DATE),COUNTRY_CITY_CUSTOMER DESC;

-- month report for the pizza_size CUBE
SELECT  EXTRACT(MONTH FROM CUSTOMER_SALE_DATE),PIZZA_SIZE,COUNT(*) AS pizza_order
FROM sa_transactions
GROUP BY CUBE(EXTRACT(MONTH FROM CUSTOMER_SALE_DATE),PIZZA_SIZE)
HAVING EXTRACT(MONTH FROM CUSTOMER_SALE_DATE) IS NOT NULL
ORDER BY EXTRACT(MONTH FROM CUSTOMER_SALE_DATE),PIZZA_SIZE DESC;

--CUBE daily pizza orders by pizza_name CUBE
SELECT  CUSTOMER_SALE_DATE, PIZZA_NAME, COUNT(*) AS pizza_order
FROM sa_transactions
GROUP BY CUBE(CUSTOMER_SALE_DATE, PIZZA_NAME)
HAVING CUSTOMER_SALE_DATE IS NOT NULL AND PIZZA_NAME IS NOT NULL 
ORDER BY CUSTOMER_SALE_DATE, PIZZA_NAME DESC;