alter session set current_schema = SA_TRANSACTIONS;

--month pizza orders by pizza_name CUBE
SELECT  EXTRACT(MONTH FROM CUSTOMER_SALE_DATE) as month,GROUPING(EXTRACT(month FROM CUSTOMER_SALE_DATE)) as grouping_month,  PIZZA_NAME,GROUPING(PIZZA_NAME) as grouping_name,COUNT(*) AS pizza_order
FROM sa_transactions
GROUP BY CUBE(EXTRACT(MONTH FROM CUSTOMER_SALE_DATE), PIZZA_NAME)
HAVING EXTRACT(MONTH FROM CUSTOMER_SALE_DATE) IS NOT NULL AND PIZZA_NAME IS NOT NULL 
ORDER BY EXTRACT(MONTH FROM CUSTOMER_SALE_DATE), PIZZA_NAME DESC;


-- month report for the country CUBE
SELECT  EXTRACT(MONTH FROM CUSTOMER_SALE_DATE) as month,GROUPING(EXTRACT(month FROM CUSTOMER_SALE_DATE)) as grouping_month,COUNTRY_CITY_CUSTOMER as town_and_country,GROUPING(COUNTRY_CITY_CUSTOMER) as grouping_country,COUNT(*) AS pizza_order
FROM sa_transactions
GROUP BY CUBE(EXTRACT(MONTH FROM CUSTOMER_SALE_DATE),COUNTRY_CITY_CUSTOMER)
HAVING EXTRACT(MONTH FROM CUSTOMER_SALE_DATE) IS NOT NULL and COUNTRY_CITY_CUSTOMER IS NOT NULL
ORDER BY EXTRACT(MONTH FROM CUSTOMER_SALE_DATE),COUNTRY_CITY_CUSTOMER DESC;

-- month report for the pizza_size CUBE
    SELECT  EXTRACT(MONTH FROM CUSTOMER_SALE_DATE) as month,GROUPING(EXTRACT(month FROM CUSTOMER_SALE_DATE)) as grouping_month,PIZZA_SIZE,GROUPING(PIZZA_SIZE) as grouping_size,COUNT(*) AS pizza_order
    FROM sa_transactions
    GROUP BY CUBE(EXTRACT(MONTH FROM CUSTOMER_SALE_DATE),PIZZA_SIZE)
    HAVING EXTRACT(MONTH FROM CUSTOMER_SALE_DATE) IS NOT NULL and PIZZA_SIZE IS NOT NULL
    ORDER BY EXTRACT(MONTH FROM CUSTOMER_SALE_DATE),PIZZA_SIZE DESC;