CREATE USER SA_PIZZERIAS
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_pizzerias_data_01;
GRANT CONNECT,RESOURCE TO SA_PIZZERIAS;

CREATE USER SA_PIZZA
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_pizza_data_01;
GRANT CONNECT,RESOURCE TO SA_PIZZA;

CREATE USER SA_TRANSACTIONS
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_fact_sales_data_01;
GRANT CONNECT,RESOURCE TO SA_TRANSACTIONS;

CREATE USER SA_FACT_SALES
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_fact_sales_data_01;
GRANT CONNECT,RESOURCE TO SA_FACT_SALES;

CREATE USER SA_SALES
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_sales_data_01;
GRANT CONNECT,RESOURCE TO SA_SALES;

CREATE USER SA_COUNTRIES
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_countries_data_01;
GRANT CONNECT,RESOURCE TO SA_COUNTRIES;

CREATE USER DW_CL
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_dw_cl_01;    
GRANT CONNECT,CREATE VIEW,RESOURCE TO DW_CL;


CREATE USER DW_DATA
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_dw_data_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DW_DATA;


CREATE USER SAL_DW_CL
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_dw_star_cls_01;

GRANT CONNECT,CREATE VIEW,RESOURCE TO SAL_DW_CL;

CREATE USER SAL_CL
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sal_cl_01;

GRANT CONNECT,CREATE VIEW,RESOURCE TO SAL_CL;



CREATE USER SA_DATE
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_date_01;

GRANT CONNECT,CREATE VIEW,RESOURCE TO SA_DATE;


CREATE USER SA_LOCATION
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_location_01;

GRANT CONNECT,CREATE VIEW,RESOURCE TO SA_LOCATION;

CREATE USER SA_SOLD_NUMBER
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_sold_number_data_01;

GRANT CONNECT,CREATE VIEW,RESOURCE TO SA_SOLD_NUMBER;


CREATE USER DM_PIZZERIAS
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_pizzerias_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_PIZZERIAS;

-- User: DM_THEATER
CREATE USER SA_CUSTOMER
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_owner_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO SA_CUSTOMER;

CREATE USER DM_PERIOD
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_period_01;

GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_PERIOD;


